/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.apple.flink.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Data extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2934923874589451667L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Data\",\"namespace\":\"com.apple.flink.avro\",\"fields\":[{\"name\":\"word\",\"type\":\"string\"},{\"name\":\"sleepMs\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Data> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Data> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Data> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Data> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Data> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Data to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Data from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Data instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Data fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence word;
  private int sleepMs;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Data() {}

  /**
   * All-args constructor.
   * @param word The new value for word
   * @param sleepMs The new value for sleepMs
   */
  public Data(java.lang.CharSequence word, java.lang.Integer sleepMs) {
    this.word = word;
    this.sleepMs = sleepMs;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return word;
    case 1: return sleepMs;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: word = (java.lang.CharSequence)value$; break;
    case 1: sleepMs = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'word' field.
   * @return The value of the 'word' field.
   */
  public java.lang.CharSequence getWord() {
    return word;
  }


  /**
   * Sets the value of the 'word' field.
   * @param value the value to set.
   */
  public void setWord(java.lang.CharSequence value) {
    this.word = value;
  }

  /**
   * Gets the value of the 'sleepMs' field.
   * @return The value of the 'sleepMs' field.
   */
  public int getSleepMs() {
    return sleepMs;
  }


  /**
   * Sets the value of the 'sleepMs' field.
   * @param value the value to set.
   */
  public void setSleepMs(int value) {
    this.sleepMs = value;
  }

  /**
   * Creates a new Data RecordBuilder.
   * @return A new Data RecordBuilder
   */
  public static com.apple.flink.avro.Data.Builder newBuilder() {
    return new com.apple.flink.avro.Data.Builder();
  }

  /**
   * Creates a new Data RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Data RecordBuilder
   */
  public static com.apple.flink.avro.Data.Builder newBuilder(com.apple.flink.avro.Data.Builder other) {
    if (other == null) {
      return new com.apple.flink.avro.Data.Builder();
    } else {
      return new com.apple.flink.avro.Data.Builder(other);
    }
  }

  /**
   * Creates a new Data RecordBuilder by copying an existing Data instance.
   * @param other The existing instance to copy.
   * @return A new Data RecordBuilder
   */
  public static com.apple.flink.avro.Data.Builder newBuilder(com.apple.flink.avro.Data other) {
    if (other == null) {
      return new com.apple.flink.avro.Data.Builder();
    } else {
      return new com.apple.flink.avro.Data.Builder(other);
    }
  }

  /**
   * RecordBuilder for Data instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Data>
    implements org.apache.avro.data.RecordBuilder<Data> {

    private java.lang.CharSequence word;
    private int sleepMs;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.apple.flink.avro.Data.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.word)) {
        this.word = data().deepCopy(fields()[0].schema(), other.word);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.sleepMs)) {
        this.sleepMs = data().deepCopy(fields()[1].schema(), other.sleepMs);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Data instance
     * @param other The existing instance to copy.
     */
    private Builder(com.apple.flink.avro.Data other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.word)) {
        this.word = data().deepCopy(fields()[0].schema(), other.word);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sleepMs)) {
        this.sleepMs = data().deepCopy(fields()[1].schema(), other.sleepMs);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'word' field.
      * @return The value.
      */
    public java.lang.CharSequence getWord() {
      return word;
    }


    /**
      * Sets the value of the 'word' field.
      * @param value The value of 'word'.
      * @return This builder.
      */
    public com.apple.flink.avro.Data.Builder setWord(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.word = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'word' field has been set.
      * @return True if the 'word' field has been set, false otherwise.
      */
    public boolean hasWord() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'word' field.
      * @return This builder.
      */
    public com.apple.flink.avro.Data.Builder clearWord() {
      word = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'sleepMs' field.
      * @return The value.
      */
    public int getSleepMs() {
      return sleepMs;
    }


    /**
      * Sets the value of the 'sleepMs' field.
      * @param value The value of 'sleepMs'.
      * @return This builder.
      */
    public com.apple.flink.avro.Data.Builder setSleepMs(int value) {
      validate(fields()[1], value);
      this.sleepMs = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'sleepMs' field has been set.
      * @return True if the 'sleepMs' field has been set, false otherwise.
      */
    public boolean hasSleepMs() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'sleepMs' field.
      * @return This builder.
      */
    public com.apple.flink.avro.Data.Builder clearSleepMs() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Data build() {
      try {
        Data record = new Data();
        record.word = fieldSetFlags()[0] ? this.word : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.sleepMs = fieldSetFlags()[1] ? this.sleepMs : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Data>
    WRITER$ = (org.apache.avro.io.DatumWriter<Data>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Data>
    READER$ = (org.apache.avro.io.DatumReader<Data>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.word);

    out.writeInt(this.sleepMs);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.word = in.readString(this.word instanceof Utf8 ? (Utf8)this.word : null);

      this.sleepMs = in.readInt();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.word = in.readString(this.word instanceof Utf8 ? (Utf8)this.word : null);
          break;

        case 1:
          this.sleepMs = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










