/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.apple.flink.avro;

@org.apache.avro.specific.AvroGenerated
public interface Protocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Protocol\",\"namespace\":\"com.apple.flink.avro\",\"types\":[{\"type\":\"record\",\"name\":\"Data\",\"fields\":[{\"name\":\"word\",\"type\":\"string\"},{\"name\":\"sleepMs\",\"type\":\"int\"}]}],\"messages\":{}}");

  @org.apache.avro.specific.AvroGenerated
  public interface Callback extends Protocol {
    public static final org.apache.avro.Protocol PROTOCOL = com.apple.flink.avro.Protocol.PROTOCOL;
  }
}